# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84826e26be7bf4cca85489ee07e8a41c3568db21880b28c80bed0ffb1ed29a2dd935f320e04c8a3d39360e46578e7f73efc219c8b423540b02c3abea79535330

test:
  secret_key_base: 68f5b3fe939e4e6ec859e15137ded0d218d9761c5a5e2788b89279c1313da6b14e31461411e1c1482d1345b51cd3bed22d2547c3d485270b6305a71218e133f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
