# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e423babde14fee5d7f6e8321a697697a2519772c028168b8cbb707b90d34a336cc2410cf7370bf4814e48cf8946f132f2e16b74002317001395a51a410d7234c

test:
  secret_key_base: f9e25ffaa286457ea12d92bc1184c89f8cd256d67d6cc19eeea637c929a41e69e83b5e918b8e7481cf1c3ba56c69e67c137cedc30b721d08a7f0b10ce7da145d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
