# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4ff927e48d5a9e2dd218b6cab4d137b839465433db81e8a65089a5e2c9fcc922b165f53407a57ca7b7e6691b55c1515b01edbad80333b1f7eff083e991e8ee0

test:
  secret_key_base: 66d6aecee2d552991f063dec2a1d88063627cc3ea0852d6a9feb56f2a2543471209fb296f074438c12c1e62fa3075d0bb9e1a30e2d597f4c4f7c026267dd7bb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
